### ISSUE TITLE
Dead link in the doc page 

### ISSUE THREAD

**Issue by vykhand** [Azure/cortana-intelligence-personalized-offers#5]
One link leads to missing page

https://github.com/Azure/cortana-intelligence-personalized-offers/blob/master/Automated%20Deployment%20Guide/Post%20Deployment%20Instructions.md

> For more information on how to monitor DocumentDB take a look at the documentation [here](https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-accounts.md).

**Comment by ghost** [comment]
The issue should be fixed now. Thank you for letting me know.
